name: Compile binaries

on:
    release:
        types: [ published ]

jobs:
    compile:
        name: Compile binaries
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v3
            -   name: Setup Deno
                uses: denoland/setup-deno@v1
                with:
                    deno-version: v1.x
            -   name: Compile
                run: deno task compile
            -   name: Upload Linux binary
                uses: actions/upload-artifact@v3
                with:
                    name: ticket-bot-linux-x86_64
                    path: ./ticket-bot-linux-x86_64
            -   name: Upload Windows binary
                uses: actions/upload-artifact@v3
                with:
                    name: ticket-bot-windows-msvc
                    path: ./ticket-bot-windows-msvc.exe
    upload:
        needs: compile
        runs-on: ubuntu-latest
        steps:
            -   name: Download artifacts
                uses: actions/download-artifact@v3
                with:
                    name: ticket-bot-linux-x86_64
            -   name: Download artifacts
                uses: actions/download-artifact@v3
                with:
                    name: ticket-bot-windows-msvc
            -   name: Upload artifacts to release
                uses: actions/upload-release-asset@v1
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                with:
                    upload_url: "https://uploads.github.com/repos/Pulsar-Dev/link-tickets/releases/latest/assets?name=ticket-bot-linux-x86_64"
                    asset_path: ./ticket-bot-linux-x86_64
                    asset_name: ticket-bot-linux-x86_64
                    asset_content_type: 'application/octet-stream'