name: Compile binaries

on:
    release:
        types: [published]

jobs:
    compile:
        name: Compile binaries
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Setup Deno
              uses: denoland/setup-deno@v1
              with:
                deno-version: v1.x
            - name: Compile
              run: deno task compile
            - name: Upload
              uses: actions/upload-artifact@v2
              with:
                  name: ticket-bot-linux-x86_64
                  retention-days: 1
                  path: ticket-bot-linux-x86_64
            - name: Upload to release
              uses: xresloader/upload-to-github-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.RELASE_TOKEN }}
              with:
                 file: ticket-bot-linux-x86_64
                 update_latest_release: true

