name: Compile binaries

on:
    release:
        types: [ published ]

jobs:
    compile:
        name: Compile binaries
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v4
            -   name: Setup Deno
                uses: denoland/setup-deno@v1
                with:
                    deno-version: v1.x
            -   name: Compile
                run: deno task compile
            -   name: Upload Linux binary
                uses: actions/upload-artifact@v4
                with:
                    name: ticket-bot-linux-x86_64
                    path: ./ticket-bot-linux-x86_64
            -   name: Upload Windows binary
                uses: actions/upload-artifact@v4
                with:
                    name: ticket-bot-windows-msvc
                    path: ./ticket-bot-windows-msvc.exe
    upload:
        needs: compile
        runs-on: ubuntu-latest
        steps:
            -   name: Download artifacts
                uses: actions/download-artifact@v4
                with:
                    name: ticket-bot-linux-x86_64
            -   name: Download artifacts
                uses: actions/download-artifact@v4
                with:
                    name: ticket-bot-windows-msvc
            -   name: Upload Linux binary to release
                uses: ncipollo/release-action@v1
                with:
                    token: ${{ secrets.RELEASE_TOKEN }}
                    artifacts: "ticket-bot-linux-x86_64"
                    artifactErrorsFailBuild: true
                    allowUpdates: true